README修正
msteq/SunUpHabits pull request #3
Opened 2024-09-30 07:22 UTC by msteq

READMEを修正いたしました。ご確認の程お願いいたします。

2024-09-30 12:05 UTC, busitora requested changes
コメントしました！

2024-09-30 12:05 UTC, busitora commented on README.md
> +私自身、健康的な朝の習慣を身につけようと意識的に取り組んでいましたが、仕事等に追われる忙しい朝にモチベーションを維持することは難しく感じました。時間が限られている中で、朝のルーティンを続けるのは簡単ではなく、つい習慣が崩れてしまうことが多かったです。このような経験から、自分一人で習慣を続けることが難しいと感じる方々が、より効果的に習慣化を進められるようなサポートが必要だと思いました。そこで、朝の
「意識的に取り組んでいました」の具体的なエピソードや状況はありますか？

2024-09-30 12:05 UTC, busitora commented on README.md
> +差別化ポイントは、モーニングルーティンに特化している点と、コミュニティを通じた相互サポートができる点です。多くの習慣化サポートアプリは、幅広い習慣やタスクを扱いますが、本アプリは朝の時間帯にフォーカスすることで、特定のニーズに応えるサービスとなっています。
具体的にどういったアプリが競合になりますか？

2024-10-01 08:57 UTC, msteq commented on README.md
> +私自身、健康的な朝の習慣を身につけようと意識的に取り組んでいましたが、仕事等に追われる忙しい朝にモチベーションを維持することは難しく感じました。時間が限られている中で、朝のルーティンを続けるのは簡単ではなく、つい習慣が崩れてしまうことが多かったです。このような経験から、自分一人で習慣を続けることが難しいと感じる方々が、より効果的に習慣化を進められるようなサポートが必要だと思いました。そこで、朝の
お忙しい中コメントいただき、ありがとうございます。具体的なエピソードとして、私自身、早起きや運動、勉強に意識的に取り組んでいます。例えば、毎朝6時に起きることを目標にし、最初はアラームを複数セットしたり、夜遅くまでのスマホ使用を控えたりするなど、少しずつ生活習慣を変える努力をしました。また、朝の運動も取り入れるため、簡単なストレッチやウォーキングを実践しましたが、忙しい仕事のスケジュールの中で継続するのは難しいと感じました。勉強についても、朝の時間を利用して資格試験の勉強を始めようとしたのですが、長続きしないことが多く、モチベーションを保つのが課題でした。
このような経験を経て、一人では難しいと感じる部分があり、他の人と進捗を共有し合うことで、より効果的に習慣を続けられる仕組みがあれば、モチベーションの維持に役立つと考えるようになりました。

2024-10-01 08:58 UTC, msteq commented on README.md
> +差別化ポイントは、モーニングルーティンに特化している点と、コミュニティを通じた相互サポートができる点です。多くの習慣化サポートアプリは、幅広い習慣やタスクを扱いますが、本アプリは朝の時間帯にフォーカスすることで、特定のニーズに応えるサービスとなっています。
コメントいただき、ありがとうございます。競合としては、HabiticaやHabitify、Streaks、Stridesだと考えていますが、どれも個人の習慣管理に焦点を当てている点が特徴だと思います。Habiticaはゲーム性があり、HabitifyやStreaks、Stridesは進捗管理やタスクの追跡に優れていると思いますが、これらは主に個人が習慣を記録・管理することに重点を置いていると思います。これに対して、本アプリはモーニングルーティンに特化しているだけでなく、他のユーザーとの共有や相互の評価を通じて、コミュニティ全体でモチベーションを維持し合う仕組みを提供できると考えています。

2024-10-05 05:33 UTC, Mariko222 commented
ご回答いただきありがとうございます。
以下、気になった点のコメントになります。
***
- 達成の「見える化」は検討されておりますでしょうか？
  例えば「◯日継続できた」バッジみたいなのをルーティンに設定できたり、過去の進捗や結果をグラフやスタンプカードみたいな形で振り返られると、モチベーションの観点からも視覚化できて良いのではと思いました。
- 使用予定のDBやフレームワーク、デプロイ先など使用技術の記載をお願いいたします。

2024-10-07 07:29 UTC, msteq commented
コメントいただき、ありがとうございます。

> * 達成の「見える化」は検討されておりますでしょうか？
ユーザーがルーティンを実行したかどうか、その結果を集計し可視化できる「達成率進捗可視化」機能と、習慣が達成された日をカレンダー形式で表示し、未達成日は空白にする「カレンダー表示」機能を追加したいと思います。

> * 使用予定のDBやフレームワーク、デプロイ先など使用技術の記載をお願いいたします。
使用技術は以下を想定しています。
・フロントエンド：Rails7.2.1 / Ruby3.3.0
・バックエンド：Rails7.2.1 / Ruby3.3.0
・CSSフレームワーク：Tailwind / daisyUI
・インフラ：データベースサーバ：PostgreSQL
・インフラ：Webアプリケーションサーバ：Render

ご確認のほどよろしくお願いいたします。

2024-10-07 12:42 UTC, busitora commented
LGTMです!
がんばってください :tada:

2024-10-07 12:43 UTC, busitora approved these changes

2024-10-11 06:15 UTC, merged